// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLnCnGCD8jpltBxKRjGX52Ash5A9-tOY8',
    appId: '1:794924891841:web:cd67249a0f98b8d2c2de40',
    messagingSenderId: '794924891841',
    projectId: 'coletafacil-4532f',
    authDomain: 'coletafacil-4532f.firebaseapp.com',
    storageBucket: 'coletafacil-4532f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfrsfdU2aIofs8DMz0Vc1gKY7heJ3kpw',
    appId: '1:794924891841:android:6770c291cdb752bbc2de40',
    messagingSenderId: '794924891841',
    projectId: 'coletafacil-4532f',
    storageBucket: 'coletafacil-4532f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT4m2kZdEEb14dgCUTovjIGXDHjCsGcc0',
    appId: '1:794924891841:ios:0ef87b7917371738c2de40',
    messagingSenderId: '794924891841',
    projectId: 'coletafacil-4532f',
    storageBucket: 'coletafacil-4532f.firebasestorage.app',
    iosBundleId: 'com.example.tercafeira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT4m2kZdEEb14dgCUTovjIGXDHjCsGcc0',
    appId: '1:794924891841:ios:0ef87b7917371738c2de40',
    messagingSenderId: '794924891841',
    projectId: 'coletafacil-4532f',
    storageBucket: 'coletafacil-4532f.firebasestorage.app',
    iosBundleId: 'com.example.tercafeira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLnCnGCD8jpltBxKRjGX52Ash5A9-tOY8',
    appId: '1:794924891841:web:60d3f2fed0b6e263c2de40',
    messagingSenderId: '794924891841',
    projectId: 'coletafacil-4532f',
    authDomain: 'coletafacil-4532f.firebaseapp.com',
    storageBucket: 'coletafacil-4532f.firebasestorage.app',
  );

}